#!/bin/sh

GIT_WORK_TREE=/var/app/ git checkout -f

DARIUS_RAILS_APP_HOME=/var/app/rails/newstagger
cd ${DARIUS_RAILS_APP_HOME}
exec bundle
exec rake darius:deploy:post_git_update RAILS_ENV=production
